"""RoboChallenge Table30v2 — data_config / embodiments / mixtures.

Auto-discovered by ``starVLA.dataloader.gr00t_lerobot.registry.discover_and_merge``.

Datasets live at::

    playground/Datasets/RoboChallenge_table30v2/lerobot/<task>/

each generated by ``examples/RoboChallenge_table30v2/train_files/convert_robochallenge_to_lerobot.py``.

Schema (single-arm: UR5 / ARX5 / DOS-W1 — see converter):
* observation.state (7,) = joint_positions(6) + gripper_width(1)
* action            (8,) = ee_positions(7 quat: tx,ty,tz,rx,ry,rz,rw) + gripper_width(1)
* video keys vary by embodiment (see ``CAMERAS`` in the converter).
"""
from starVLA.dataloader.gr00t_lerobot.datasets import ModalityConfig
from starVLA.dataloader.gr00t_lerobot.transform.base import ComposedModalityTransform
from starVLA.dataloader.gr00t_lerobot.transform.state_action import (
    StateActionToTensor,
    StateActionTransform,
)
from starVLA.dataloader.gr00t_lerobot.embodiment_tags import EmbodimentTag


class _RoboChallengeUR5Config:
    """RoboChallenge Table30v2 — UR5 single-arm (2 cameras: cam_global, cam_arm).
    Schema (see converter):
        observation.state  (7,) = joint_positions(6) + gripper_width(1)
        action             (8,) = ee_positions(7 quat: tx,ty,tz,rx,ry,rz,rw) + gripper_width(1)
    """
    embodiment_tag = EmbodimentTag.UR5
    video_keys = ["video.cam_global", "video.cam_arm"]
    state_keys = ["state.joint_positions", "state.gripper_width"] 
    action_keys = ["action.ee_positions", "action.gripper_width", "action.ee_positions", "action.gripper_width"] # @JinhuiYE 通过padding 快速对齐到 统一维度
    language_keys = ["annotation.human.task_description"]

    observation_indices = [0]
    stride = 1
    action_indices = list(range(1, (50*stride) + 1, stride)) # stride 用来调整 fps / stride
    # 1 开始是因为查看转 lerobot 时候， action raw 的 timeslot 是 state + 1
    
    state_indices = [0]

    def modality_config(self):
        return {
            "video":     ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.video_keys),
            "state":     ModalityConfig(delta_indices=self.state_indices, modality_keys=self.state_keys),
            "action":    ModalityConfig(delta_indices=self.action_indices,      modality_keys=self.action_keys),
            "language":  ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.language_keys),
        }

    def transform(self):
        # apply_to must be deduplicated: StateActionToTensor processes keys by list order
        # and would fail on the 2nd occurrence of the same key (already a Tensor).
        # modality_keys in modality_config() keeps duplicates intentionally so that
        # _pack_sample concatenates them to reach 16-dim (aligned with ALOHA).
        unique_action_keys = list(dict.fromkeys(self.action_keys))
        return ComposedModalityTransform(transforms=[
            StateActionToTensor(apply_to=self.state_keys),
            StateActionTransform(
                apply_to=self.state_keys,
                normalization_modes={k: "q99" for k in self.state_keys},
            ),
            StateActionToTensor(apply_to=unique_action_keys),
            StateActionTransform(
                apply_to=unique_action_keys,
                normalization_modes={k: "q99" for k in unique_action_keys},
            ),
        ])


class _RoboChallengeARX5Config(_RoboChallengeUR5Config):
    """ARX5 single-arm (3 cameras: cam_global, cam_arm, cam_side).

    Schema (see converter):
        observation.state  (7,) = joint_positions(6) + gripper_width(1)
        action             (8,) = ee_positions(7 quat: tx,ty,tz,rx,ry,rz,rw) + gripper_width(1)
    """
    embodiment_tag = EmbodimentTag.ARX5
    video_keys = ["video.cam_global", "video.cam_arm", "video.cam_side"]


class _RoboChallengeDOSW1Config(_RoboChallengeUR5Config):
    """DOS-W1 single-arm (3 cameras: cam_high, cam_left_wrist, cam_right_wrist).

    Schema (see converter):
        observation.state  (7,) = joint_positions(6) + gripper_width(1)
        action             (8,) = ee_positions(7 quat: tx,ty,tz,rx,ry,rz,rw) + gripper_width(1)
    """
    embodiment_tag = EmbodimentTag.DOS_W1
    video_keys = ["video.cam_high", "video.cam_left_wrist", "video.cam_right_wrist"]


class _RoboChallengeAlohaConfig:
    """ALOHA bimanual (3 cameras: cam_high, cam_left_wrist, cam_right_wrist).

    Schema (see converter):
        observation.state (14,) = L.joint(6) + L.grip(1) + R.joint(6) + R.grip(1)
        action            (16,) = L.ee(7)    + L.grip(1) + R.ee(7)    + R.grip(1)
    """
    embodiment_tag = EmbodimentTag.ALOHA
    video_keys = ["video.cam_high", "video.cam_left_wrist", "video.cam_right_wrist"]
    state_keys = [
        "state.joint_positions_left",  "state.gripper_width_left",
        "state.joint_positions_right", "state.gripper_width_right",
    ]
    action_keys = [
        "action.ee_positions_left",  "action.gripper_width_left",
        "action.ee_positions_right", "action.gripper_width_right",
    ]
    language_keys = ["annotation.human.task_description"]

    observation_indices = [0]
    stride = 1
    action_indices = list(range(1, (50*stride) + 1, stride)) # stride 用来调整 fps / stride
    state_indices = [0]

    def modality_config(self):
        return {
            "video":     ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.video_keys),
            "state":     ModalityConfig(delta_indices=self.state_indices, modality_keys=self.state_keys),
            "action":    ModalityConfig(delta_indices=self.action_indices,      modality_keys=self.action_keys),
            "language":  ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.language_keys),
        }

    def transform(self):
        return ComposedModalityTransform(transforms=[
            StateActionToTensor(apply_to=self.state_keys),
            StateActionTransform(
                apply_to=self.state_keys,
                normalization_modes={k: "q99" for k in self.state_keys},
            ),
            StateActionToTensor(apply_to=self.action_keys),
            StateActionTransform(
                apply_to=self.action_keys,
                normalization_modes={k: "q99" for k in self.action_keys},
            ),
        ])


ROBOT_TYPE_CONFIG_MAP = {
    "ur5_robochallenge":   _RoboChallengeUR5Config(),
    "arx5_robochallenge":  _RoboChallengeARX5Config(),
    "dosw1_robochallenge": _RoboChallengeDOSW1Config(),
    "aloha_robochallenge": _RoboChallengeAlohaConfig(),
}

DATASET_NAMED_MIXTURES = {
    # --- minimal walk-through (1 task) ---
    "robochallenge_table30v2_shred_paper": [
        ("lerobot/shred_paper", 1.0, "ur5_robochallenge"),
    ],
    "robochallenge_table30v2_lint_roller": [
        ("lerobot/lint_roller_remove_dirt", 1.0, "aloha_robochallenge"),
    ],
    # --- UR5 single-arm ---
    "robochallenge_table30v2_ur5_all": [
        ("lerobot/arrange_fruits",      1.0, "ur5_robochallenge"),
        ("lerobot/item_classification", 1.0, "ur5_robochallenge"),
        ("lerobot/shred_paper",         1.0, "ur5_robochallenge"),
    ],
    # --- ARX5 single-arm ---
    "robochallenge_table30v2_arx5_all": [
        ("lerobot/arrange_flowers",              1.0, "arx5_robochallenge"),
        ("lerobot/hang_the_cup",                 1.0, "arx5_robochallenge"),
        ("lerobot/pick_out_the_green_blocks",    1.0, "arx5_robochallenge"),
        ("lerobot/press_the_button",             1.0, "arx5_robochallenge"),
        ("lerobot/turn_on_the_light_switch",     1.0, "arx5_robochallenge"),
        ("lerobot/water_the_flowers",            1.0, "arx5_robochallenge"),
        ("lerobot/wipe_the_table",               1.0, "arx5_robochallenge"),
    ],
    # --- DOS-W1 single-arm ---
    "robochallenge_table30v2_dosw1_all": [
        # ("lerobot/fold_the_clothes",                1.0, "dosw1_robochallenge"),
        ("lerobot/hold_the_tray_with_both_hands",   1.0, "dosw1_robochallenge"),
        ("lerobot/place_objects_into_desk_drawer",  1.0, "dosw1_robochallenge"),
        ("lerobot/put_in_pen_container",            1.0, "dosw1_robochallenge"),
        ("lerobot/put_the_shoes_back",              1.0, "dosw1_robochallenge"),
        ("lerobot/stack_bowls",                     1.0, "dosw1_robochallenge"),
        ("lerobot/sweep_the_trash",                 1.0, "dosw1_robochallenge"),
        ("lerobot/tidy_up_the_makeup_table",        1.0, "dosw1_robochallenge"),
        ("lerobot/tie_a_knot",                      1.0, "dosw1_robochallenge"),
        ("lerobot/untie_the_shoelaces",             1.0, "dosw1_robochallenge"),
    ],
    # --- ALOHA bimanual ---
    "robochallenge_table30v2_aloha_all": [
        ("lerobot/lint_roller_remove_dirt",                 1.0, "aloha_robochallenge"),
        ("lerobot/pack_the_items",                          1.0, "aloha_robochallenge"),
        ("lerobot/pack_the_toothbrush_holder",              1.0, "aloha_robochallenge"),
        ("lerobot/paint_jam",                               1.0, "aloha_robochallenge"),
        ("lerobot/put_the_books_back",                      1.0, "aloha_robochallenge"),
        ("lerobot/put_the_pencil_case_into_the_schoolbag",  1.0, "aloha_robochallenge"),
        ("lerobot/scoop_with_a_small_spoon",                1.0, "aloha_robochallenge"),
        ("lerobot/stamp_positioning",                       1.0, "aloha_robochallenge"),
        ("lerobot/wipe_the_blackboard",                     1.0, "aloha_robochallenge"),
        ("lerobot/wrap_with_a_soft_cloth",                  1.0, "aloha_robochallenge"),
    ],

    


}


# --- all tasks combined (ur5 + arx5 + dosw1 + aloha) ---
DATASET_NAMED_MIXTURES["robochallenge_table30v2_all"] = [
    entry
    for key in [
        "robochallenge_table30v2_ur5_all",
        "robochallenge_table30v2_arx5_all",
        # "robochallenge_table30v2_dosw1_all",
        "robochallenge_table30v2_aloha_all",
    ]
    for entry in DATASET_NAMED_MIXTURES[key]
]  